#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

## Script To Manage Brightness For Archcraft (in Wayland).

# Get brightness
get_backlight() {
  LIGHT=$(printf "%.0f\n" "$(($(brightnessctl g)/960))")
	echo "${LIGHT}%"
}

# Increase brightness
inc_backlight() {
	#light -A 5
	brightnessctl set +10%
 # printf "%.0f\n" "$(light)" | awk '{if ($1+0 < 10) {print 0$1} else {print $1}}' >>"$HOME"/.config/eww/eww_sway/deflisten_condition/brightness
}

# Decrease brightness
dec_backlight() {
	#light -U 5
	brightnessctl set 10%-
  #printf "%.0f\n" "$(light)" | awk '{if ($1+0 < 10) {print 0$1} else {print $1}}' >>"$HOME"/.config/eww/eww_sway/deflisten_condition/brightness
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_backlight
elif [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
else
	get_backlight
fi
